language: python
python:
- '2.7'
before_install:
- sudo apt-get install -qq graphviz
install: pip install -q -r requirements.txt --use-mirrors
script: sphinx-build -nW -b html -d _build/doctrees . _build/html
deploy:
  provider: s3
  access_key_id: <%= ENV['aws_key_prod'] %>
  secret_access_key: <%= ENV['aws_secret_prod] %>
  bucket: "vui-docs"
  skip_cleanup: true
  local-dir: _build/html
env:
  global:
  - secure: jVTao8o4AgS8sRwygnDD61xluYnyFlRYIgcFspklofQiEJQ4RPJ+PZ06kWLlOlFXE/iASV3Leiak6zyg3/0LF3KKxx+Oxl2iW2MMc3kY8TBB2dgIjaTeaHyaDEVIugrdrP8GLvvCX2tpIEL0Y5Lyu2371um4dlv+elYmNdrDPJ8=
  - secure: RaJOD/IftN1NYFIGhiYWacRjMXo6afiIGrt3tvbbnHgIaoWfYynurpPKRTW4ABHhmByOcKAq4akkHLw+1+mq6OzFrcze3Vd1JI5LYeR08VeiSJPk+adqYSg0vZKJLkZ2NZCHquUcjIfq6w3ijcqfCIjDTICoR1Kv0IomWxp/vrw=
